baseURL = "https://mansoorbarri.com"
defaultContentLanguage = "en"
languageCode = "en"

title = "Mansoor Barri"

theme = ["gokarna"]

pygmentsStyle = "monokai"

pluralizelisttitles = false

enableEmoji = true

# Automatically generate robots.txt
enableRobotsTXT = false

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 2
    ordered = false

[menu]
  [[menu.main]]
    name = "Guides"
    url = "/guides/"
    weight = 1

  [[menu.main]]
    name = "Newsletter"
    url = "/newsletter/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3 

  [[menu.main]]
    pre = "<span data-feather='download'></span>"
    url = "/downloads/"
    weight = 4

  [params]
  # URL for the avatar on homepage
  avatarURL = "/img/logo/main.webp"

  # Show recent post on home page
  showPostsOnHomePage = "recent"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-m"

  # Description to display on homepage
  description = "At mansoorbarri.com, we offer a wealth of IT knowledge through guides & newsletters about IT; specifically Linux."

  # Accent color is displayed when you hover over <a> tags (original #FF4D4D)
  accentColor = "#ff0005"

  customHeadHTML = '''
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5174559718233522"
       crossorigin="anonymous"></script>
  '''


  # Keywords relevant for SEO
  metaKeywords = ["Blog", "Mansoor Barri", "Tech", "Hacking"]

  socialIcons = [
      {name = "medium", url = "https://medium.com/@mansoorbarri/"},
      {name = "github", url = "https://github.com/mansoorbarri/"},      
      {name = "twitter", url = "https://twitter.com/mansoorbarri"},
      {name = "linkedin", url = "https://www.linkedin.com/in/mansoorbarri/"},      
    ]

  # Footer text
  footer = "Mansoor Barri"
