baseURL = "https://mansoorbarri.com"
defaultContentLanguage = "en"
languageCode = "en"

title = "Mansoor Barri"

theme = ["hugo-redirect", "gokarna"]

pygmentsStyle = "monokai"

pluralizelisttitles = false

# Automatically generate robots.txt
enableRobotsTXT = false

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 2
    ordered = false

[menu]
  [[menu.main]]
    name = "Guides"
    url = "/guides/"
    weight = 1

  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 2

  [[menu.main]]
    name = "Write-ups"
    url = "/write-ups/"
    weight = 3

  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 4

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5

  [[menu.main]]
    identifier = "rss"
    url = "/sitemap.xml"
    weight = 6
    pre = "<span data-feather='rss'></span>"

  [params]
  # URL for the avatar on homepage
  avatarURL = "https://mansoorbarri.com/logo/main.webp"

  # Show recent post on home page
  showPostsOnHomePage = "recent"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-m"

  # Description to display on homepage
  description = "At mansoorbarri.com, we offer a wealth of IT knowledge through tutorials, articles, and writeups, along with IT services for individuals and businesses."

  # Accent color is displayed when you hover over <a> tags (original #FF4D4D)
  accentColor = "#ff0005"

  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["Blog", "Mansoor Barri", "Tech", "Hacking"]

  socialIcons = [
      {name = "twitter", url = "https://twitter.com/mansoorbarri"},
      {name = "linkedin", url = "https://www.linkedin.com/in/mansoor-barri-845596228/"},      
      {name = "github", url = "https://github.com/mansoorbarri/"},      
    ]

  # Footer text
  footer = "Mansoor Barri"