
baseURL = "https://mansoorbarri.com"
defaultContentLanguage = "en"
languageCode = "en"

title = "Mansoor Barri"

theme = ["hugo-redirect", "gokarna"]

pygmentsStyle = "monokai"

pluralizelisttitles = false

# Automatically generate robots.txt
enableRobotsTXT = true

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 2
    ordered = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "How to"
    url = "/how-to/"
    weight = 2

  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 3

  [[menu.main]]
    name = "Write-ups"
    url = "/write-ups/"
    weight = 4

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 5

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 6
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/mansoorbarri"
    weight = 7
    pre = "<span data-feather='github'></span>"

  [params]
  # URL for the avatar on homepage
  avatarURL = "/images/main.webp"

  enableEmoji = true

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-m"

  # Description to display on homepage
  description = "A website where you can get guides, articles, and write-ups written in simple, layman's language. I also offer IT services, so please feel free to contact us at mansoorbarri.com/contact-us/."

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  customHeadHTML = '''
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9209590432348224"
     crossorigin="anonymous"></script>
  '''

  enableRobotsTXT = true


  # Keywords relevant for SEO
  metaKeywords = ["blog", "Mansoor", "Barri", "Tech", "Hacking"]

  socialIcons = [
      {name = "twitter", url = "https://twitter.com/mansoorbarri"},
      {name = "linkedin", url = "https://www.linkedin.com/in/mansoor-barri-845596228/"},
      {name = "discord", url = "https://discord.com/users/770850821441191966"},      
      {name = "tryhackme", url = "https://tryhackme.com/p/MansoorBarri"},
    ]

  # Footer text
  footer = "Mansoor Barri"